spring:
  application:
    name: be-storytellers
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/storytellers}
    username: ${DB_USER:dev}
    password: ${DB_PASS:dev}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port:  ${REDIS_PORT:6380}
      password: ${REDIS_PASSWORD:root}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:354500739862-49ihelflu36lmkp7dpnek031ais3fuid.apps.googleusercontent.com}
            client-secret: ${GOOGLE_CLIENT_SECRET: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}
            scope:
              - email
              - profile
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB
  threads:
    virtual:
      enabled: true

app:
  jwt:
    secret: ${JWT_SECRET:supersecretkey256bitminimumrequiredforsecurity}
    access-token-expiry: 300
    refresh-token-expiry: 604800
  aws:
    region: ${AWS_REGION:ap-southeast-1}
    s3:
      bucket: ${S3_BUCKET:projectdemo01}
  cors:
    allowed-origin: ${CORS_ALLOWED_ORIGIN:http://localhost:3000}
  frontend-url: ${FRONTEND_URL:http://localhost:3000}
  payment:
    mock: ${PAYMENT_MOCK:true}

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs
